CREATE TABLE `spring_session` (
    `PRIMARY_ID` char(36) NOT NULL,
    `SESSION_ID` char(36) NOT NULL,
    `CREATION_TIME` bigint(20) NOT NULL,
    `LAST_ACCESS_TIME` bigint(20) NOT NULL,
    `MAX_INACTIVE_INTERVAL` int(11) NOT NULL,
    `EXPIRY_TIME` bigint(20) NOT NULL,
    `PRINCIPAL_NAME` varchar(300) DEFAULT NULL,
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (`PRIMARY_ID`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

ALTER TABLE `spring_session`
    ADD PRIMARY KEY (`PRIMARY_ID`),
    ADD UNIQUE KEY `SPRING_SESSION_IX1` (`SESSION_ID`),
    ADD KEY `SPRING_SESSION_IX2` (`EXPIRY_TIME`),
    ADD KEY `SPRING_SESSION_IX3` (`PRINCIPAL_NAME`);

CREATE TABLE `spring_session_attributes` (
    `SESSION_PRIMARY_ID` char(36) NOT NULL,
    `ATTRIBUTE_NAME` varchar(200) NOT NULL,
    `ATTRIBUTE_BYTES` blob NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;